### ISSUE TITLE
r2lang import error

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2-rlang#16]
I've been trying to write a plugin for r2 and want to register it as a core call in the same way that the pimp util does. However, when i call "import r2lang", i get the following:

```
[0x00400470]> !python ./radare2.py
Traceback (most recent call last):
  File "./radare2.py", line 4, in <module>
    import r2lang
ImportError: No module named r2lang
```

I have also tried starting it via `r2 -i ./radare2.py` and get the same error both ways.

I'm using the latest Docker built image of r2.

**Comment by XVilka** [comment]
@bannsec yes, it is tied to `r2 -H` output, of course it should put plugins in `.local`. This failure is the result of fixing this issue https://github.com/radare/radare2/issues/9083

**Comment by XVilka** [comment]
Related: https://github.com/radareorg/radare2/issues/17239

**Comment by trufae** [comment]
We need to add r2r tests in here to ensure that plugins actually run, not just build

**Comment by benner** [comment]
I solved with

```
% r2pm -i rlang-python
```
