### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by pantrombka** [radareorg/radare2-rlang#19]
When I'm trying compile radarer2-rlang a got a error:
```
python/anal.c: In function ‘py_anal’:
python/anal.c:128:8: error: ‘RAnalValue’ {aka ‘struct r_anal_value_t’} has no member named ‘sel’; did you mean ‘seg’?
  128 |   val->sel = getI (dict, "sel"); \
      |        ^~~
python/anal.c:196:7: note: in expansion of macro ‘READ_VAL’
  196 |       READ_VAL(tmplst, op->src[i], tmpreg)
      |       ^~~~~~~~
python/anal.c:128:8: error: ‘RAnalValue’ {aka ‘struct r_anal_value_t’} has no member named ‘sel’; did you mean ‘seg’?
  128 |   val->sel = getI (dict, "sel"); \
      |        ^~~
python/anal.c:201:5: note: in expansion of macro ‘READ_VAL’
  201 |     READ_VAL(tmpdst, op->dst, tmpreg)
```
      |     ^~~~~~~~

**Expected behavior**

**Possible fix**

**Screenshots**

**Additional context**

**Comment by XVilka** [comment]
Please provide more information about:
- Platform, OS (or Linux distribution) used
- Python version
- `radare2 -v` output
- How do you installed radare2?

**Comment by pantrombka** [comment]
Ubuntu 20.04 LTS
Python 3.8.2 
radare2 4.6.0-git 25012 @ linux-x86-64 git.4.4.0-489-g5b101b652
commit: 5b101b6521d7a916d2b0709cdc64eb0eb1b520f7 build: 2020-07-29__09:53:26
I downloaded radare2 from github
gcc version 9.3.0

**Comment by XVilka** [comment]
Fixed in https://github.com/radareorg/radare2-rlang/commit/4ef78d9ed83db18bf1e163316a18b5121ce1ea0c
