### ISSUE TITLE
Original git history was removed

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2-rlang#20]

**Comment by XVilka** [comment]
Could be grafted from radare2-bindings:
- https://git.wiki.kernel.org/index.php/GraftPoint
- https://blog.developer.atlassian.com/grafting-earlier-history-with-git/
- https://stackoverflow.com/questions/47928855/how-do-i-combine-several-git-repositories-without-breaking-file-history

**Comment by XVilka** [comment]
Fixed, see https://github.com/radareorg/radare2-rlang/commits/master
