### ISSUE TITLE
Fix r2lang plugins after radare2 refactoring of RBin and RAnal+RAsm merge

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2-rlang#3]
Since the API will change drastically, both implementation and documentation (in r2book) should be fixed.

**Comment by radare** [comment]
how's your future yourself going on?

**Comment by XVilka** [comment]
RBin refactor and RAsm/RAnal wasn't finished yet?

**Comment by trufae** [comment]
this will take a lot of time to get fixed and its an obvious task to be done when the core apis change. for now i think its fine to close this issue.
