### ISSUE TITLE
limits of Python bindings to write plugins

### ISSUE THREAD

**Issue by Wenzel** [radareorg/radare2-rlang#4]
Hi !

I developed an [IO and debug plugins](https://github.com/Wenzel/radare2-extras/tree/vmi/vmi) for radare2 in C, and i wanted to port them in Python.

As there was no support to register a debug plugin in Python with `r2lang`, i forked `radare2-bindings` and started to implement the required [function and interface](https://github.com/Wenzel/radare2-bindings/blob/debug_python/libr/lang/p/python/debug.c).

However, i realized that i would not be able to fully translate my C debug plugin to python, because of limitation of the bindings:

For example my `__attach` implementation requires to access multiple sub-fields of the `RDebug *` structure, (`dbg->iob.io->desc->data`), and from this pointer, i need to recreate my `RIOVmi *`.
~~~C
static int __attach(RDebug *dbg, int pid) {
    RIODesc *desc = NULL;
    RIOVmi *rio_vmi = NULL;
    status_t status = 0;

    printf("Attaching to pid %d...\n", pid);

    desc = dbg->iob.io->desc;
    rio_vmi = desc->data;
~~~

while I'm implementing this in `libr/lang/p/python/debug.c`, i don't really know how to pass the content of the `RDebug *` structure:
~~~C
static int py_debug_attach(RDebug *dbg, int pid) {
	printf("py %s\n", __func__);
        PyObject *arglist = Py_BuildValue (?????);
        PyObject *result = PyEval_CallObject (py_debug_attach_cb, arglist);
}
~~~

Which could allow me to implement my debugger and have the same arguments:
~~~Python
import r2lang
def pydebug(_):

    def attach(rdebug, pid):
        print("attaching !")

print("Registering Python debug plugin...")
print(r2lang.plugin("debug", pydebug))
~~~

So what is the status of the Python bindings ?
What solution do you recommend ?

cc @XVilka 

Thanks !

**Comment by radare** [comment]
so...

> On 20 Apr 2018, at 15:54, Mathieu Tarral <notifications@github.com> wrote:
> 
> so the “problem” is only with the debug plugin, not the io one
> 
> that's correct.
> 
> because you want to get the address of the process selected using rekall?
> 
> I would need a set of symbols:
> 
> PsActiveProcessHead kernel address
> offset of ImageFileName in _EPROCESS struct
> offset of Win32StartAddress in _ETHREAD struct
> ntdll!LdrInitializeThunk userspace address
> etc…
> 

this is a task for rbin, not rdebug or rio. so i would go for just doing a rekall plugin in python. to get all those flags into r2.

> Ta place my breakpoints at the right location while the process is created and intercept the first thread.
> 
> i mean.. isnt it supposed to work only with memory dumps?
> 
> That's the thing.
> I worked with Michael Cohen to add a new VMI Address Space in Rekall in order to work directly on top of the physical memory, thanks to Libvmi:
> https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/addrspaces/vmi.py#L15 <https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/addrspaces/vmi.py#L15>
> This allows me to do memory forensics without having to generate a RAM dump.
> 
> 
ah thats cool! that may safe some GB of useless dumps in /tmp :P
> And using Rekall API in python, i can extract some symbols on the fly:
> 
>     s = session.Session(
>             filename="vmi://xen/windows_7",
>             autodetect=["rsds"],
>             logger=logging.getLogger(),
>             autodetect_build_local='none',
>             format='data',
>             profile_path=[
>                 "http://profiles.rekall-forensic.com"
> ])

what i see here is r2 and rekall doing separate connections to the xen machine with vmi. so its not reusing r_io

from an r2pipe script you can read the opened file uri and reuse-it from that script and then set the flags to make r2 autocomplete those addresses. you can set the breakpoints using names instead of offsets then.

another option would be to make this debug plugin instantiate a python vm and run rekall from inside, instead of making the whole plugin in python

**Comment by radare** [comment]
Try the corebind cmd approach i suggested in telegram

**Comment by trufae** [comment]
ping.  its been 2 years since this issue was open. Is this issue still happening? can we close it?

thanks @Wenzel !

**Comment by Wenzel** [comment]
Hi @trufae ,

I will close this issue as i'm not working on r2vli anymore.

Thanks !
